/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as InflationRouteImport } from './routes/inflation'
import { Route as EtfScreenerRouteImport } from './routes/etf-screener'
import { Route as EmergencyFundRouteImport } from './routes/emergency-fund'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as EconomicCalendarRouteImport } from './routes/economic-calendar'
import { Route as DividendScreenerRouteImport } from './routes/dividend-screener'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditCardPayoffRouteImport } from './routes/credit-card-payoff'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompoundInterestRouteImport } from './routes/compound-interest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStocksRouteImport } from './routes/dashboard.stocks'
import { Route as DashboardCryptoRouteImport } from './routes/dashboard.crypto'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const InflationRoute = InflationRouteImport.update({
  id: '/inflation',
  path: '/inflation',
  getParentRoute: () => rootRouteImport,
} as any)
const EtfScreenerRoute = EtfScreenerRouteImport.update({
  id: '/etf-screener',
  path: '/etf-screener',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyFundRoute = EmergencyFundRouteImport.update({
  id: '/emergency-fund',
  path: '/emergency-fund',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicCalendarRoute = EconomicCalendarRouteImport.update({
  id: '/economic-calendar',
  path: '/economic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendScreenerRoute = DividendScreenerRouteImport.update({
  id: '/dividend-screener',
  path: '/dividend-screener',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardPayoffRoute = CreditCardPayoffRouteImport.update({
  id: '/credit-card-payoff',
  path: '/credit-card-payoff',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundInterestRoute = CompoundInterestRouteImport.update({
  id: '/compound-interest',
  path: '/compound-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStocksRoute = DashboardStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCryptoRoute = DashboardCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => DashboardRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compound-interest': typeof CompoundInterestRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/credit-card-payoff': typeof CreditCardPayoffRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/dividend-screener': typeof DividendScreenerRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/etf-screener': typeof EtfScreenerRoute
  '/inflation': typeof InflationRoute
  '/investment': typeof InvestmentRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/net-worth': typeof NetWorthRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/savings': typeof SavingsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/stocks': typeof DashboardStocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compound-interest': typeof CompoundInterestRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/credit-card-payoff': typeof CreditCardPayoffRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/dividend-screener': typeof DividendScreenerRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/etf-screener': typeof EtfScreenerRoute
  '/inflation': typeof InflationRoute
  '/investment': typeof InvestmentRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/net-worth': typeof NetWorthRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/savings': typeof SavingsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/stocks': typeof DashboardStocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/compound-interest': typeof CompoundInterestRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/credit-card-payoff': typeof CreditCardPayoffRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/dividend-screener': typeof DividendScreenerRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/emergency-fund': typeof EmergencyFundRoute
  '/etf-screener': typeof EtfScreenerRoute
  '/inflation': typeof InflationRoute
  '/investment': typeof InvestmentRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/net-worth': typeof NetWorthRoute
  '/privacy': typeof PrivacyRoute
  '/retirement': typeof RetirementRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/savings': typeof SavingsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/tools': typeof ToolsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/stocks': typeof DashboardStocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compound-interest'
    | '/contact'
    | '/cookie-policy'
    | '/credit-card-payoff'
    | '/dashboard'
    | '/disclaimer'
    | '/dividend-screener'
    | '/economic-calendar'
    | '/editorial-policy'
    | '/emergency-fund'
    | '/etf-screener'
    | '/inflation'
    | '/investment'
    | '/loan'
    | '/mortgage'
    | '/net-worth'
    | '/privacy'
    | '/retirement'
    | '/rss.xml'
    | '/savings'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/test'
    | '/tools'
    | '/article/$slug'
    | '/category/$slug'
    | '/dashboard/crypto'
    | '/dashboard/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compound-interest'
    | '/contact'
    | '/cookie-policy'
    | '/credit-card-payoff'
    | '/dashboard'
    | '/disclaimer'
    | '/dividend-screener'
    | '/economic-calendar'
    | '/editorial-policy'
    | '/emergency-fund'
    | '/etf-screener'
    | '/inflation'
    | '/investment'
    | '/loan'
    | '/mortgage'
    | '/net-worth'
    | '/privacy'
    | '/retirement'
    | '/rss.xml'
    | '/savings'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/test'
    | '/tools'
    | '/article/$slug'
    | '/category/$slug'
    | '/dashboard/crypto'
    | '/dashboard/stocks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/compound-interest'
    | '/contact'
    | '/cookie-policy'
    | '/credit-card-payoff'
    | '/dashboard'
    | '/disclaimer'
    | '/dividend-screener'
    | '/economic-calendar'
    | '/editorial-policy'
    | '/emergency-fund'
    | '/etf-screener'
    | '/inflation'
    | '/investment'
    | '/loan'
    | '/mortgage'
    | '/net-worth'
    | '/privacy'
    | '/retirement'
    | '/rss.xml'
    | '/savings'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/test'
    | '/tools'
    | '/article/$slug'
    | '/category/$slug'
    | '/dashboard/crypto'
    | '/dashboard/stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CompoundInterestRoute: typeof CompoundInterestRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CreditCardPayoffRoute: typeof CreditCardPayoffRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  DividendScreenerRoute: typeof DividendScreenerRoute
  EconomicCalendarRoute: typeof EconomicCalendarRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  EmergencyFundRoute: typeof EmergencyFundRoute
  EtfScreenerRoute: typeof EtfScreenerRoute
  InflationRoute: typeof InflationRoute
  InvestmentRoute: typeof InvestmentRoute
  LoanRoute: typeof LoanRoute
  MortgageRoute: typeof MortgageRoute
  NetWorthRoute: typeof NetWorthRoute
  PrivacyRoute: typeof PrivacyRoute
  RetirementRoute: typeof RetirementRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SavingsRoute: typeof SavingsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  ToolsRoute: typeof ToolsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inflation': {
      id: '/inflation'
      path: '/inflation'
      fullPath: '/inflation'
      preLoaderRoute: typeof InflationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etf-screener': {
      id: '/etf-screener'
      path: '/etf-screener'
      fullPath: '/etf-screener'
      preLoaderRoute: typeof EtfScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-fund': {
      id: '/emergency-fund'
      path: '/emergency-fund'
      fullPath: '/emergency-fund'
      preLoaderRoute: typeof EmergencyFundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-calendar': {
      id: '/economic-calendar'
      path: '/economic-calendar'
      fullPath: '/economic-calendar'
      preLoaderRoute: typeof EconomicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividend-screener': {
      id: '/dividend-screener'
      path: '/dividend-screener'
      fullPath: '/dividend-screener'
      preLoaderRoute: typeof DividendScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-card-payoff': {
      id: '/credit-card-payoff'
      path: '/credit-card-payoff'
      fullPath: '/credit-card-payoff'
      preLoaderRoute: typeof CreditCardPayoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound-interest': {
      id: '/compound-interest'
      path: '/compound-interest'
      fullPath: '/compound-interest'
      preLoaderRoute: typeof CompoundInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stocks': {
      id: '/dashboard/stocks'
      path: '/stocks'
      fullPath: '/dashboard/stocks'
      preLoaderRoute: typeof DashboardStocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crypto': {
      id: '/dashboard/crypto'
      path: '/crypto'
      fullPath: '/dashboard/crypto'
      preLoaderRoute: typeof DashboardCryptoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCryptoRoute: typeof DashboardCryptoRoute
  DashboardStocksRoute: typeof DashboardStocksRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCryptoRoute: DashboardCryptoRoute,
  DashboardStocksRoute: DashboardStocksRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CompoundInterestRoute: CompoundInterestRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CreditCardPayoffRoute: CreditCardPayoffRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  DividendScreenerRoute: DividendScreenerRoute,
  EconomicCalendarRoute: EconomicCalendarRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  EmergencyFundRoute: EmergencyFundRoute,
  EtfScreenerRoute: EtfScreenerRoute,
  InflationRoute: InflationRoute,
  InvestmentRoute: InvestmentRoute,
  LoanRoute: LoanRoute,
  MortgageRoute: MortgageRoute,
  NetWorthRoute: NetWorthRoute,
  PrivacyRoute: PrivacyRoute,
  RetirementRoute: RetirementRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SavingsRoute: SavingsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  ToolsRoute: ToolsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
